### ISSUE TITLE
support encoded polyline

### ISSUE THREAD

**Issue by cyril23** [DaddyWarbucks/static-google-map#2]
I would love to see the encoded polyline supported:

See https://developers.google.com/maps/documentation/maps-static/dev-guide#EncodedPolylines

> Instead of a series of locations, you may instead declare a path as an encoded polyline by using the `enc:` prefix within the location declaration of the path.
> 
> The following example outlines the course of the Alaska Highway from Dawson Creek, BC to Delta Junction, AK with an encoded polyline:
>
> ```
> https://maps.googleapis.com/maps/api/staticmap
> ?size=400x400&center=59.900503,-135.478011&zoom=4
> &path=weight:3%7Ccolor:orange%7Cenc:_fisIp~u%7CU}%7Ca@pytA_~b@hhCyhS~hResU%7C%7Cx@oig@rwg@amUfbjA}f[roaAynd@%7CvXxiAt{ZwdUfbjAewYrqGchH~vXkqnAria@c_o@inc@k{g@i`]o%7CF}vXaj\h`]ovs@?yi_@rcAgtO%7Cj_AyaJren@nzQrst@zuYh`]v%7CGbldEuzd@%7C%7Cx@spD%7CtrAzwP%7Cd_@yiB~vXmlWhdPez\_{Km_`@~re@ew^rcAeu_@zhyByjPrst@ttGren@aeNhoFemKrvdAuvVidPwbVr~j@or@f_z@ftHr{ZlwBrvdAmtHrmT{rOt{Zz}E%7Cc%7C@o%7CLpn~AgfRpxqBfoVz_iAocAhrVjr@rh~@jzKhjp@``NrfQpcHrb^k%7CDh_z@nwB%7Ckb@a{R%7Cyh@uyZ%7CllByuZpzw@wbd@rh~@%7C%7CFhqs@teTztrAupHhyY}t]huf@e%7CFria@o}GfezAkdW%7C}[ocMt_Neq@ren@e~Ika@pgE%7Ci%7CAfiQ%7C`l@uoJrvdAgq@fppAsjGhg`@%7ChQpg{Ai_V%7C%7Cx@mkHhyYsdP%7CxeA~gF%7C}[mv`@t_NitSfjp@c}Mhg`@sbChyYq}e@rwg@atFff}@ghN~zKybk@fl}A}cPftcAite@tmT__Lha@u~DrfQi}MhkSqyWivIumCria@ciO_tHifm@fl}A{rc@fbjAqvg@rrqAcjCf%7Ci@mqJtb^s%7C@fbjA{wDfs`BmvEfqs@umWt_Nwn^pen@qiBr`xAcvMr{Zidg@dtjDkbM%7Cd_@
> &key=YOUR_API_KEY
> ```

affects: https://github.com/DaddyWarbucks/static-google-map/blob/master/src/strategies/path.js

- easy solution: push a given polyline to the urlParts
- advanced solution: provide a function to encode points to an encoded polyline and push your polyline to the urlParts

**Comment by DaddyWarbucks** [comment]
You can actually already achieve this by simply passing the polyline to the `points` property of a path. For example
```js
staticMapUrl({
  key: 'YOUR_KEY',
  size: '600x600',
  paths: [{
      color: 'red',
      points: 'enc:enrjF~blePve|Mwp`T' // be sure to include `enc:`
  }]
)}
```
I'll update the docs.

Cheers!

**Comment by cyril23** [comment]
Works like a charm, thanks! And even saves me some characters, because the manual `myUrl += "&path=color:red%7Cenc" + encodeURIComponent(polyline)` I had before somehow encoded the polyline string longer than needed.

By the way I'm using this package for the polyline https://www.npmjs.com/package/google-polyline

I'll close this issue now.

**Comment by DaddyWarbucks** [comment]
Glad its working for you! This is the first issue and you are the first confirmed user of of the package so that is exciting!
