### ISSUE TITLE
The typings does not reflect on the expected code

### ISSUE THREAD

**Issue by SkyaTura** [DaddyWarbucks/static-google-map#7]
When testing the example on the readme, as is, on TypeScript, will throw a type error because the definitions of `PathGroup` and `Marker` are different from the current implementation.

Would you mind if I send a PR converting the project to use TS as main language instead of only declare types externally?

I think this could be better maintainable, since errors like this would be checked upon compile of the lib.

**Comment by DaddyWarbucks** [comment]
Sure! I think thats a great idea!

**Comment by SkyaTura** [comment]
I'll begin as soon as I get some spare time then. 😊
